// <auto-generated />
using System;
using Doitclick.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doitclick.Data.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    partial class SecurityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Doitclick.Models.Security.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones");
                });

            modelBuilder.Entity("Doitclick.Models.Security.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Nombre");

                    b.Property<int?>("OrzanizacionId");

                    b.Property<int>("RolPadreId");

                    b.HasKey("Id");

                    b.HasIndex("OrzanizacionId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Doitclick.Models.Security.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("Clave");

                    b.Property<string>("Correo");

                    b.Property<string>("EstadoCuenta");

                    b.Property<string>("Identificador");

                    b.Property<string>("Nombre");

                    b.Property<string>("TokenRecuerdaAcceso");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Doitclick.Models.Security.Rol", b =>
                {
                    b.HasOne("Doitclick.Models.Security.Organizacion", "Orzanizacion")
                        .WithMany("Roles")
                        .HasForeignKey("OrzanizacionId");
                });
#pragma warning restore 612, 618
        }
    }
}
